spring:
  datasource:
    url: jdbc:mysql://<PROD_HOST>:3306/jobtracker
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

server:
  port: 8080

logging:
  level:
    root: INFO
